"""Opt-in continuation to the original list or an explicitly selected full JD.

Observe only the application's current DOM, never cookies/passwords or new
network requests. A readable matching list proves availability of that list,
not that a particular account has authenticated. No login is submitted here.
"""
from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
import json
import time
from urllib.parse import parse_qsl, urlsplit

from .contracts import CrawlError


def matching_list_signature(adapter, expected_url, page):
    """Reject unrelated queries, detail/recommendation pages and empty lists."""
    expected = urlsplit(adapter.accept_url(expected_url))
    actual = urlsplit(adapter.accept_url(page.url))
    if (expected.scheme, expected.netloc, expected.path.rstrip('/')) != (
            actual.scheme, actual.netloc, actual.path.rstrip('/')):
        return None
    # accept_url removes only the adapter's known tracking parameters. All
    # remaining filters, including repeated keys, must match. Never log values.
    wanted = parse_qsl(expected.query, keep_blank_values=True)
    present = parse_qsl(actual.query, keep_blank_values=True)
    if sorted(wanted) != sorted(present):
        return None
    cards = adapter.cards(page)
    if not cards:
        return None
    return hashlib.sha256('\n'.join(card.id for card in cards).encode()).hexdigest()


@dataclass(frozen=True)
class DetailTarget:
    row_id: str
    expected_url: str = field(repr=False)


@dataclass(frozen=True)
class ReturnedDetail:
    """One-use owner-worker handoff. No HTML, parsed JD or credentials queued."""
    target: DetailTarget
    signature: str
    backend: object = field(repr=False)


def pending_detail_target(state):
    """Only the next unfinished explicit selection can consume a returned JD.

    Preserve the collector's order. Do not skip a failed earlier item to adopt
    a recommended/unselected/later job merely because its page is readable.
    """
    if state.get('phase') != 'collect':
        return None
    selection = set(state.get('selection', ()))
    for row in state.get('cards', ()):
        if row['id'] not in selection or row.get('status') == 'ok':
            continue
        if row.get('status') in {'discovered', 'opening', 'manual_required', 'paused'}:
            return DetailTarget(row['id'], row['url'])
        return None
    return None


def matching_detail_signature(adapter, expected_url, page):
    """Match the selected entity and complete parsed content, without navigation.

    A platform may establish URL aliases using its identity validator. Without
    that validator require the exact accepted URL (only known trackers removed).
    """
    expected = adapter.accept_url(expected_url, detail=True)
    actual = adapter.accept_url(page.url, detail=True)
    identity = getattr(adapter, 'job_identity', None)
    if callable(identity):
        if identity(expected) != identity(actual):
            return None
    elif expected != actual:
        return None
    validate = getattr(adapter, 'validate_detail_identity', None)
    if callable(validate):
        validate(expected, page)
    parsed = adapter.detail(page)
    # Validate through the same data boundary used by the collector. An adapter
    # returning a snippet, invalid fields or an empty body is not a ready JD.
    from ..models import JobRecord
    try:
        record = JobRecord(**parsed, url=actual, platform=adapter.key,
                           source_mode='browser_fetch')
        if record.evidence_level != 'full_text':
            raise ValueError('not full text')
        # No timestamp generated by JobRecord or transient surrounding DOM:
        # compare only the adapter's complete data on consecutive observations.
        body = json.dumps(parsed, sort_keys=True, ensure_ascii=False, allow_nan=False)
    except (TypeError, ValueError, OverflowError) as exc:
        raise CrawlError('invalid_job_data') from exc
    return hashlib.sha256(body.encode('utf-8')).hexdigest()


@dataclass
class _Watch:
    backend: object
    expected_url: str
    expires: float
    next_check: float
    signature: str | None = None
    detail_target: DetailTarget | None = None
    surface: str | None = None


class LoginReturnManager:
    """Owner-worker-only watcher; bounded, cancellable and never restarted on boot."""
    def __init__(self, *, clock=time.monotonic, interval=1.0, timeout=600.0):
        self.clock, self.interval, self.timeout = clock, interval, timeout
        self._watches: dict[str, _Watch] = {}

    def arm(self, state, backend):
        self._watches.clear()  # The service owns one active browser session.
        if state.get('auto_continue_after_login') is not True:
            return False
        now = self.clock()
        self._watches[state['id']] = _Watch(backend, state['search_url'], now+self.timeout, now,
            detail_target=pending_detail_target(state))
        return True

    def disarm(self, ident):
        return self._watches.pop(ident, None) is not None

    def _attention(self, service, ident, watch):
        # DOM access can yield to pause or a new action; never overwrite its
        # newer state when reporting an observation error.
        with service._lock:
            if self._watches.get(ident) is not watch:
                return
            self.disarm(ident)
            if service._busy or service._cancel.is_set() or service._shutdown.is_set():
                return
            state = service._load(ident)
            if state.get('status') == 'waiting_manual':
                service._save(state, login_continuation='needs_attention')

    def tick(self, service):
        """Called on the same worker as Playwright, after pumping page events."""
        for ident, watch in tuple(self._watches.items()):
            with service._lock:
                if service._busy or service._shutdown.is_set():
                    return
                now = self.clock()
                if now < watch.next_check:
                    continue
                watch.next_check = now + self.interval
                try:
                    state = service._load(ident)
                except Exception:
                    self.disarm(ident)
                    continue
                if (service._cancel.is_set() or service._backends.get(ident) is not watch.backend
                        or state.get('authentication') != 'manual_pending'
                        or state.get('status') != 'waiting_manual'):
                    self.disarm(ident)
                    service._save(state, login_continuation='cancelled')
                    continue
                if now >= watch.expires:
                    self.disarm(ident)
                    service._save(state, login_continuation='timed_out')
                    continue
            try:
                # No service lock during DOM access: pause/stop can win while
                # Playwright yields. Recheck ownership before submitting below.
                page = watch.backend.snapshot()
                adapter = service.registry.get(state['platform'])
                try:
                    signature = matching_list_signature(adapter, watch.expected_url, page)
                except CrawlError as exc:
                    # HTTP-to-browser handoffs use the selected detail as their
                    # search_url. That surface is correctly not a list, but can
                    # still be the explicitly selected complete JD below.
                    if exc.code != 'not_job_list' or watch.detail_target is None:
                        raise
                    signature = None
                surface = 'list'
                if signature is None and watch.detail_target is not None:
                    if pending_detail_target(state) != watch.detail_target:
                        self._attention(service, ident, watch)
                        continue
                    signature = matching_detail_signature(
                        adapter, watch.detail_target.expected_url, page)
                    surface = 'detail'
            except CrawlError as exc:
                if exc.code in {'manual_required', 'not_job_list', 'wrong_platform', 'invalid_url',
                                'not_job_url', 'job_identity_mismatch', 'structure_changed',
                                'jd_incomplete', 'invalid_job_data', 'credential_url'}:
                    watch.signature = watch.surface = None
                    continue
                self._attention(service, ident, watch)
                continue
            except Exception:
                self._attention(service, ident, watch)
                continue
            with service._lock:
                if (self._watches.get(ident) is not watch or service._busy
                        or service._cancel.is_set() or service._shutdown.is_set()
                        or service._backends.get(ident) is not watch.backend):
                    self.disarm(ident)
                    continue
                if signature is None or (surface, signature) != (watch.surface, watch.signature):
                    watch.surface, watch.signature = surface, signature
                    continue
                # Two stable local observations; remove before enqueueing so
                # reentrant events cannot submit the action twice.
                self.disarm(ident)
                if surface == 'detail':
                    service._save(state, status='queued', login_continuation='checking_detail')
                    service._submit('resume_returned_detail', ident,
                        ReturnedDetail(watch.detail_target, signature, watch.backend))
                else:
                    action = 'resume' if state.get('phase') == 'collect' else 'capture'
                    service._save(state, status='queued', login_continuation='resumed')
                    service._submit(action, ident)
                return
